---
abstract: 'first-class switch statements'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
  - 'TOBYINK <tobyink@cpan.org>'
build_requires:
  Test::More: '0.61'
  Test::Warn: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.021, CPAN::Meta::Converter version 2.140640'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Smart-Dispatch
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Smart::Dispatch:
    file: lib/Smart/Dispatch.pm
    version: '0.006'
  Smart::Dispatch::Match:
    file: lib/Smart/Dispatch/Match.pm
    version: '0.006'
  Smart::Dispatch::Table:
    file: lib/Smart/Dispatch/Table.pm
    version: '0.006'
  Syntax::Feature::Dispatcher:
    file: lib/Syntax/Feature/Dispatcher.pm
    version: '0.006'
requires:
  Moo: '0'
  Sub::Exporter: '0'
  namespace::clean: '0'
  perl: '5.010'
resources:
  Identifier: http://purl.org/NET/cpan-uri/dist/Smart-Dispatch/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Smart-Dispatch
  homepage: https://metacpan.org/release/Smart-Dispatch
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-smart-dispatch.git
version: '0.006'
